// object holding character class html / details
var characterDetails = {
	sleuth: {
			features: '<li>Increased intellect attribute</li><li>Excels at mental / puzzle encounters</li><li>Pinpoints weaknesses in enemies/ enemy tactics.</li>',
			skills: '<li><i class="fa fa-search" aria-hidden="true"></i>Analysis</li><li><i class="fa fa-book" aria-hidden="true"></i>Knowledge</li><li><i class="fa fa-eye" aria-hidden="true"></i>Notice</li>',
			description: '<p> All spies are adept at gathering information, making decisions under pressure, and creating tactical assessments on the fly – with the limited information at hand. Some use their physical ability, others their natural charisma, others still live by the skin of their teeth or by the agent at their side. For a select few, information is not merely the end result of an observation or investigation; it is a weapon that is superior to any rifle or handgun, a vessel capable of traversing the vast distances on our planet in moments, and a tool capable of breaking even the most stoic poker face.</p><p>They are some of the smartest people on the planet. Brilliant, observant, and dangerously cunning - sleuths beat their opponents long before they encounter them. They use information as formidable weapons, and their sharp minds to outthink their opponents. </p>'
	},
	pointman: {
			features: '<li>Increased efficiency attribute</li><li>Enhances team performance</li><li>Provides measure of stability during high-stakes missions</li>',
			skills: '<li><i class="fa fa-cogs" aria-hidden="true"></i>Planning</li><li><i class="fa fa-list-ol" aria-hidden="true"></i>Focus</li><li><i class="fa fa-group" aria-hidden="true"></i>Leadership</li>',
			description: "<p>They are the handlers, directors, and operators that live and breathe the spy game. Pointmen convert disadvantages into advantages, turning the tide in the gravest of circumstances. They are trained to make snap decisions, and always apply the best possible strategy in a given situation. They are bold, decisive, highly adaptive, and terrifyingly skilled individuals with an unparalleled understanding of the espionage world.</p>"
	},
	faceman: {
			features: '<li>Increased charisma attribute</li><li>Excels at social/ confidence missions</li><li>allows access to out-of-factionconnections/ contacts</li>',
			skills: '<li><i class="fa fa-low-vision" aria-hidden="true"></i>Blend</li><li><i class="fa fa-unlock" aria-hidden="true"></i>Manipulate</li><li><i class="fa fa-puzzle-piece" aria-hidden="true"></i>Networking</li>',
			description: '<p>From the voluptuous vixen to the charming rogue, the full gamut of facemen runs the length and breadth of the espionage game. Facemen are at their best when working an angle, or a con. Masters at manipulation, cold reading, and daring gambits, they do their deadliest work without firing a single shot. When it comes to social subterfuge, to “the night before and the morning after”, reading tells, or serving a cake of lies with the truth only as icing – there is no better class than the Faceman.</p> <p>They turn a simple conversation into leverage, deduce a person’s life story from how his eye twitches, and slip into social gatherings as quickly as one would into a pair of fluffy slippers. Their native tongue is impersonation; their deadliest weapon a smile or kiss.</p>'
	},
	soldier: {
			features: '<li>Increased combat attribute</li><li>Excels at firefighting and assassination</li><li>durable, reliable combatant</li>',
			skills: '<li><i class="fa fa-plus-circle" aria-hidden="true"></i>Vitals</li><li><i class="fa fa-crosshairs" aria-hidden="true"></i>Weaponry</li><li><i class="fa fa-map" aria-hidden="true"></i>Tactics</li>',
			description: '<p>The soldier is a highly trained killing machine, with his natural environment being the straight up fight. Soldiers are tough, direct, and lethal. In battle, no one dominates the field more than soldiers. Undisputed combat powerhouses; they are specialists called in to resolve bad situations turned worse. </p> <p>With bloodshed as their prayer, and Death their god, soldiers find themselves on the front lines; first to arrive and the last to leave. </p> '
	},
	scout: {
			features: '<li>Increased kinetics attribute</li><li>Excels during chase /search missions. </li><li>Melee specialist. Adept at navigation, wayfinding, and survival.</li>',
			skills: '<li><i class="fa fa-map-marker" aria-hidden="true"></i>Navigation</li><li><i class="fa fa-gear" aria-hidden="true"></i>Mechanics</li><li><i class="fa fa-low-vision" aria-hidden="true"></i>Conceal</li>',
			description: '<p>The scout is the expert tracker, survivalist, and navigator. When lost in a hostile environment, it is the scouts that shine, mainly cause they have the know-how, will, and experience to get out of difficult situations. Scouts use vehicles as if they were extensions of their own bodies. </p><p>Objects, roadblocks, and other obstacles offer little hindrance when scouts are on the move; seemingly able to defy physical laws as they go. They prefer close combat, taking advantage of their knowledge of human biology, pressure points, and kinetics. </p><p>Scouts are stealthy, silent, and efficient.</p>'
	}
}

// object holding faction data
var factions = {
	aesir: {
		history: '<p>Aesir can trace its roots from the Thirty Years’ War in 1618. In response to this war, Louis XIII of France formed a clandestine organization, called the Black Cloaks. They answered solely to the French Crown - and were intended to prevent similar incidents from happening. By the French Revolution of 1789, the Black Cloaks were forgotten by the public and the crown. However, in secret, they grew and gained independence with a roster spanning the continent. Clever book keeping allowed the State to fund the Black Cloaks, covertly and indirectly.</p><p>When the First World War erupted and plunged the entire European continent into chaos, the Black Cloaks worked to restore order. They found out that they were entirely ill equipped to deal with a crisis of that scale. In response, the Black Cloaks were dissolved and the Aesir was formed in its place - a new organization, independent from government. Englishman and MI6 Agent, Sir Benedict Marshal - was appointed its first director. Since then, they expanded their ranks, making friends and allies with operatives from other European nations. The Aesir has managed to keep the peace in the region for a few years, working in secret, keeping tabs on each of the member nations.</p><p>By the time the second world war started, the Aesir had a network of agents spanning the entire continent manipulating events from behind. Some even say the fall of the 3rd Reich was heavily influenced by the work of Aesir agents.</p> <p>Aesir has a robust pool of agents, all very talented and versatile. Holding this highly sophisticated organization together is a core group of administrators, all of which report directly to the current Director, Lady Helen Newton. They are deployed all across the globe, most in deep cover and ready to be activated at a moment’s notice.</p>',
		doctrine: '<p>Secret wars are fought everyday, and Aesir have taken it upon themselves to be the soldiers that makes sure these stay hidden. The Aesir believes that the way to win wars is by having superior knowledge and information than your enemy. They consider themselves modern knights, crusading in secret to protect the lives of the innocent against the dragons of the world.</p> ',
		orgStructure: "<p>The Aesir operates under a strict chain of command, demands absolute loyalty from its agents,  and requires absolute adherence to the organization’s core ideals.</p><p> A number of Aesir veteran agents are Cyphers and Soldiers. Their agents excel at information gathering, counter intelligence, to and the precise use of necessary force.</p><p>The Aesir’s main base of operations is located somewhere in Sweden; but it maintains a number of satellite HQs scattered across Western Europe. The entire operation is secretly funded by Aesir’s member nations, and is required, as per the charter, to publish an annual report directly addressed to the respective heads-of-state about the activities of the organization.</p> <p>This report, is of course, heavily edited The Aesir’s organizational structure and internal terminology is largely based on Nordic Mythology. They have an incredibly complex system in place with fixed ranks and adopted call-signs. All qualified agents may take these names or adapt any of the aliases used by related mythological figures as their official call-sign and/or designation.</p>"
	},
	ksos: {
		history: '<p>KSOS was formed from the fragments of the KGB and expanded their ranks from the neighboring Slavic nations after the fall of the USSR - making them one of the newer agencies formed.</p> <p>KSOS’ objective is simple - yet ambitious - unification of the Slavic states. They believe that the time for selfish, isolationist ideas is over, that true unification may only be achieved through cooperation and transparency. </p><p>The start of the Commission was a rocky one - with internal distrust amongst the founders mostly due to fear of a KGB mole. They finally managed to unite under the command of Leonard Doshtoyevski, a former general of the Soviet Army, who successfully exposed the feared mole and dealt with him.</p> <p>What most consider as the cold war, remained cold mostly due to the interference and work of KSOS double agents who worked inside the Kremlin and alongside Lensmen agents. By their record, the world nearly faced nuclear winter about 4 times in those years, and almost escalated to open combat at least 6 times.</p> <p>The Commission was also a key player in the Russian-Afghan war, where KSOS agents helped keep other nations and factions from getting involved - a request from the Lensmen. Years later KSOS regretted that decision as it only placed a highly volatile new regime in an already volatile area. </p>',
		doctrine: '<p>KSOS is unusually distrustful of advanced technology and prefer their to use the “old ways.” They believe in building the right tools for the right job. KSOS is often believed to be ruthless and cruel by other agencies mostly since they believe in a overt response than a measured and appropriate one. They are, however, honourable - often going above and beyond the expectations for the sake of those they consider an ally or friend.</p>',
		orgStructure: '<p>The Commission is currently under the strong leadership of Commander Jarek Sokolowski, the first Polish Commander to receive the responsibility. Due to Jarek’s actions, KSOS has become the region’s most influential organization, despite it being a relatively new player in the espionage game. Nothing goes on in the area without his knowledge, if not his consent.</p><p>KSOS’ trainers are mainly composed of former wheelmen and soldiers - veterans of the Cold War. This makes them some of the best soldiers and pilots in the world. The training is brutal, and under Jarek’s command, fieldwork becomes even more brutal. Those who survive become agents, and those who excel become part of his special task force, the Black Paw.</p> <p>Leadership in the KSOS is determined by strict military succession and chain of command. Despite not being part of any country’s military, members are usually awarded an equivalent rank based on their experience, expertise or former military rank. They have an extensive military codex of rules and bylaws on which they base their internal politics and organizational operation. When an officer leaves his/her post, his immediate subordinate assumes the vacant position. In the event that there are several candidates for the position, a higher ranking officer or a panel of officers assigns a member to the position, usually the one with the most experience.</p>'
	},
	silentEmpire: {
		history: '<p>It has been long believed that the 3 Emperors are direct descendants of the Heavenly Brothers of myth. Despite centuries of mixed marriages and shifts in locations, all emperors can trace their linage to one family - the Huang clan. The current triumvirate consists of Emperors from the three most powerful nations in East Asia. While each leader has a public face, very few know their  full involvement in the organization.</p><p>The Silent Empire is the world’s oldest espionage organization, formed centuries ago by a small group of merchants whose trade routes spanned the whole of asia. The Silent Empire’s exploits are well kept secrets - often attributed to myth, legend, or conjecture - a popular favourite is that of the Ninja.</p><p>From what little information that has been implied, the agents of the Empire were involved in one way or another with the Mongolian invasion of China, the defeat of Magellan, the Fall of Feudal Japan, The Boxer rebellion, keeping both China and North Korea at bay.</p> ',
		doctrine: '<p>The Silent Empire of the Sacred Serpent exists to bring harmony to bring back the glory of the Eastern Empire - no matter the cost. Their power extends across generations, nations, and centuries, from the edge of the Mongolian Plains to the tip of the Indonesian Peninsula. They believe that the massive influx of new, radical ideologies has taken its toll on humanity, and the only way to fight back and bring balance to the chaotic world is through a series of subtle, yet relevant actions that ripple throughout world society. </p>',
		orgStructure: '<p>The Silent Empire is a complex organization run by 3 Emperors each with equal power. Each has regions they oversee. All three Emperors have unquestioned sway in the regions they rule over, with each area containing a massive network of agents from various walks of life - from wealthy industrialists to the lowly pier worker - all of them fiercely loyal to their liege. While there have been frequent internal conflicts among the subjects, the Emperors manage to sort them out before conflicts escalate into something significantly disruptive. </p>'
	},
	lensmen: {
		history: " <p> Officially, the Lensmen do not exist; all the branches of American government deny their existence and offer none of the judicial support that is lent to other individuals who operate within government sanction. </p> Officially, they have no base of operations, and no official government funding; Lensmen deal and dabble in the economy of the world through a confusing and often convoluted network of brokers and traders - obfuscating and complicating their paper trails; this approach means that Lensmen have some difficulty being financially liquid -  but to Lensmen, the freedom to become the shadows of shadows is a more than equitable trade in the long run. <p>Founded during the American Civil War, the Lensmen was the first time individuals from both sides of the war banded together to end it. While ultimately successful, the Lensmen suffered terrible losses during that time, most notably the assassination of one of their leaders - President Abraham Lincoln.</p> <p>Over the centuries, the Lensmen would be highly involved in several operations that would shape the country in several ways. It is believed by a few historians who are convinced of the organisation’s existence that the Lensmen anticipated a second world war, engineered the great depression, and ultimately catapulted the USA into an economic, military, technological world power in less than a decade.</p>",
		doctrine: "<p>Lensmen protocol is easy enough to understand - they seek to maintain the order of the world by their most sacred (and subversive) contribution to world policy; E Pluribus Unum. Through the individual efforts of many, the world remains one. The mark of the earliest Lensmen is obvious - it is on the great seal of the United states of America; The symbol of the Lensmen is the all-seeing-eye; also located on american currency. </p>",
		orgStructure: "<p>No one knows the exact number of Lensmen safe-houses, armories or vehicle depots; what is known is that they have full access to America's greatest weapon - the power of production.</p> <p>The Lensmen are the most well-funded espionage organization in the world, and have a steady and plentiful stream of financial assistance from their backers in the United States. </p> <p>Lensmen themselves operate in individual cells, adapting between solo operation to teams as large as small towns, as is required. Their HQ - the prism - is located several stories below the Mall of America - the perfect front to disguise a massive heat signature, as well as a large power and a data sink.</p> <p>The lensmen have full access to global reach of America's military assets, and while their methods and delivery systems are hardly subtle - their solitary nature as well as their predisposition to conspiracy, allow them efficient yet direct insertions to wherever they need to be.</p>"
	},
	kraken: {
		history: "<p>For years they have operated in secret, and have kept balanced in their role in world politics - never tipping the scale that would cause chaos - until 17 months ago. Several of the founders  mysteriously went missing, save for two. The man known only as “B26”, and his partner “Vic”, took control of the Network and began convincing its members that a global conspiracy to shut their operations down was executed. Within 48 hours several cities around the globe would report several incidents carried out under the Collective’s name - all of which involve the captivity or death of known criminals, the extortion of governments & officials, and acts bordering on terrorism. Soon, a written manifesto started popping up in every media outlet, declaring the ideals and objective of the Network. </p><p>Overnight people around the world were polarized, and the Collective’s numbers grew. </p><p>The Collective doesn't have a fixed stable of agents. Instead they function as several anonymous, independent cells with regional leadership, called Alephs. They assign tasks to specialists in the network - carried out to the best of each specialist’s abilities. Their agents may include a high school computer geek, a middle aged housewife, a law enforcer, to some of the most powerful men in office.</p> <p>None of them are agents until the second they are activated by their Alephs. The Collective is every covert organizations worst nightmare: an anonymous force of extremely loyal, innocent civilians, driven and motivated by borderline fanaticism.</p>",
		doctrine: '<p>Built on the ideals and actions of a few very talented young men, the Collective works towards changing the world into the perfect example of Organic Solidarity - no matter the cost. They offer an alternative lifestyle, a closed community free from any judgement, where age, gender, social status, and race mean nothing. In a few short months, a virtual community was formed - with each member incredibly loyal to the cause; each willing to contribute their talent - and even their lives - to the cause. They monitor information in virtually every media outlet, and they know how to use that knowledge to push their plans into action.</p>',
		orgStructure: 'Not applicable.'
	},
	order: {
		history: 'It stands for Organized Response to Despotism, Extortion and Rebellion.<p>Back in 2001, in response to the bombing of the World Trade Center, as well as the increase in international threats, the G8 heads-of-state and the UN Secretary General commissioned a small task-force to help prevent further escalation in global hot zones. </p><p>Originally set to assist the US troops in the war in the Middle East, they have expanded their operations to hot-zone theaters in the Israel-Palestine border, East-Asia, India-Pakistan, and some North African states. They have their hands full ever-since the start, and despite being incredibly well-funded and out-fitted, being stretched too thin as well as being a new covert-division has left them with little intel or influence.</p>',
		doctrine: '<p>O.R.D.E.R. is a global Peace-Keeping outfit secretly founded by the United Nations to monitor, to diffuse, and to deter renegade and destabilizing activity around the world. </p>',
		orgStructure: '<p>Commander Joseph James Jackson, a Naval Admiral and current director of O.R.D.E.R., is often described as relentless, and stubborn, despite having good intentions and an unwavering sense of integrity. His expertise and experience in various wars in his career has landed him this position as well as command of a small but most technologically advanced Naval fleet in the world. He reports directly to the UN’s current Secretary General.</p><p>The Fleet’s flagship, the Atlas, is the most advanced aircraft carrier in existence. It is considered international territory and is rumored to have the firepower to level nations. Because they are a fleet, O.R.D.E.R. does not have any permanent base of operations. The flotilla relies on accords and agreements, kept off the books, by different members of the UN.</p>'
	},
}